"""Added

Revision ID: 45e772751164
Revises: 46d2a0174c4d
Create Date: 2024-08-24 12:46:31.163526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '45e772751164'
down_revision: Union[str, None] = '46d2a0174c4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('TITLE', sa.String(), nullable=False))
    op.add_column('todos', sa.Column('DESCRIPTION', sa.String(), nullable=False))
    op.add_column('todos', sa.Column('COMPLETED', sa.Boolean(), nullable=False))
    op.add_column('todos', sa.Column('CREATED_AT', sa.DateTime(), nullable=False))
    op.add_column('todos', sa.Column('UPDATED_AT', sa.DateTime(), nullable=False))
    op.drop_column('todos', 'description')
    op.drop_column('todos', 'completed')
    op.drop_column('todos', 'title')
    op.drop_column('todos', 'created_at')
    op.drop_column('todos', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('todos', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('todos', 'UPDATED_AT')
    op.drop_column('todos', 'CREATED_AT')
    op.drop_column('todos', 'COMPLETED')
    op.drop_column('todos', 'DESCRIPTION')
    op.drop_column('todos', 'TITLE')
    # ### end Alembic commands ###
