"""Added

Revision ID: 46d2a0174c4d
Revises: aa7fa93b2c06
Create Date: 2024-08-24 12:14:31.591537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46d2a0174c4d'
down_revision: Union[str, None] = 'aa7fa93b2c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('UUID', sa.UUID(), nullable=False))
    op.create_unique_constraint(None, 'todos', ['UUID'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', schema='public', type_='unique')
    op.drop_column('todos', 'UUID')
    # ### end Alembic commands ###
